development:
  sessions:
    default:
      database: marketing_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: marketing_dev
      hosts:
        - localhost:27017
